/**
 * Lists the tools published by the running `qloo mcp` (no API key needed) and writes:
 *   - docs/qloo-tools.md                       human-readable schemas + behaviour notes + gaps
 *   - src/qloo/fixtures/tools.snapshot.ts      the same schemas as data, so sample-data mode can run without spawning qloo
 * Run: npm run docs:tools
 */
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StdioClientTransport } from "@modelcontextprotocol/sdk/client/stdio.js";
import { resolveQlooCommand } from "../src/qloo/mcp-client.js";
import type { JsonObject, ToolDef } from "../src/qloo/types.js";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const env: Record<string, string> = {};
for (const [k, v] of Object.entries(process.env)) if (v !== undefined && k !== "QLOO_API_KEY") env[k] = v; // no key: nothing live can be called

const cmd = resolveQlooCommand(process.env);
const client = new Client({ name: "shelfwise-docs", version: "0.1.0" });
await client.connect(new StdioClientTransport({ command: cmd.command, args: cmd.args, env }));
const listed = await client.listTools();
// qloo_capabilities reports readiness and the contract checksum without calling Qloo.
const caps = (await client.callTool({ name: "qloo_capabilities", arguments: {} })).structuredContent as JsonObject | undefined;
await client.close();

const tools: ToolDef[] = listed.tools.map((t) => ({
  name: t.name,
  ...(t.title ? { title: t.title } : {}),
  description: t.description ?? "",
  inputSchema: t.inputSchema as JsonObject,
}));
const harnessVersion = (JSON.parse(readFileSync(path.join(root, "node_modules/@qloo/qloo-harness/package.json"), "utf8")) as { version: string }).version;
const checksum = String(caps?.["contract_checksum"] ?? "unknown");

// ------------------------------------------------------------------ snapshot module
const snapshot: ToolDef[] = tools.map((t) => ({ name: t.name, ...(t.title ? { title: t.title } : {}), description: t.description, inputSchema: t.inputSchema }));
writeFileSync(
  path.join(root, "src/qloo/fixtures/tools.snapshot.ts"),
  `// GENERATED by \`npm run docs:tools\` from the tools/list of \`qloo mcp\` (@qloo/qloo-harness ${harnessVersion}).\n` +
    `// This is the REAL tool surface (not placeholder data); it lets sample-data mode run without starting qloo.\n` +
    `// A test fails if it drifts from the installed harness. Regenerate rather than editing.\n` +
    `import type { ToolDef } from "../types.js";\n\n` +
    `export const TOOLS_SNAPSHOT_HARNESS_VERSION = ${JSON.stringify(harnessVersion)};\n` +
    `export const TOOLS_SNAPSHOT: ToolDef[] = ${JSON.stringify(snapshot, null, 2)};\n`,
);

// ------------------------------------------------------------------ markdown
const typeOf = (s: JsonObject): string => {
  if (Array.isArray(s["enum"])) return `enum: ${(s["enum"] as unknown[]).map((v) => `\`${String(v)}\``).join(", ")}`;
  if (s["type"] === "array") {
    const items = (s["items"] ?? {}) as JsonObject;
    return `array of ${items["type"] === "string" && Array.isArray(items["enum"]) ? `enum(${(items["enum"] as string[]).join(", ")})` : String(items["type"] ?? "any")}`;
  }
  return String(s["type"] ?? "any");
};

const constraints = (s: JsonObject): string => {
  const out: string[] = [];
  for (const k of ["minLength", "minItems", "maxItems", "minimum", "maximum", "pattern", "default"]) {
    if (s[k] !== undefined) out.push(`${k}: ${typeof s[k] === "string" ? `\`${String(s[k])}\`` : JSON.stringify(s[k])}`);
  }
  return out.join("; ") || "-";
};

const cell = (s: string): string => s.replace(/\|/g, "\\|").replace(/\n/g, " ");

function toolSection(t: ToolDef): string {
  const schema = t.inputSchema;
  const props = (schema["properties"] ?? {}) as Record<string, JsonObject>;
  const required = new Set((schema["required"] ?? []) as string[]);
  const rows = Object.entries(props).map(
    ([name, p]) => `| \`${name}\` | ${cell(typeOf(p))} | ${required.has(name) ? "yes" : ""} | ${cell(constraints(p))} | ${cell(String(p["description"] ?? ""))} |`,
  );
  return [
    `### \`${t.name}\``,
    "",
    t.description,
    "",
    rows.length ? "| Argument | Type | Required | Constraints | Notes |\n| --- | --- | --- | --- | --- |\n" + rows.join("\n") : "_No arguments._",
    "",
    "Raw input schema (as published by the server):",
    "",
    "```json",
    JSON.stringify(schema, null, 2),
    "```",
    "",
  ].join("\n");
}

const md = `# Qloo tool surface used by Shelfwise

Generated by \`npm run docs:tools\` from the tools/list of the running \`qloo mcp\` server
(\`@qloo/qloo-harness\` **${harnessVersion}**, workflow contract checksum \`${checksum}\`).
Listing the tools and calling \`qloo_capabilities\` need no API key and make no network request.
Do not edit by hand; edit \`scripts/dump-tools.ts\` and regenerate.

Every workflow tool returns the same result envelope (\`schema_version "1.0-preview.1"\`):
\`status\` (\`ok | empty | needs_input | partial | degraded | error\`), \`summary\`, \`interpretation\`,
\`resolution\`, \`results\` (or \`series\` for trends), \`result_count\`, \`warnings\`, \`error\` (\`code, layer, retryable, recovery\`),
\`execution\`, and \`provenance.requests[]\` (the Qloo API requests made).

## Tools

| Tool | What it does | Shelfwise uses it for |
| --- | --- | --- |
| \`qloo_capabilities\` | Contract + readiness, no Qloo call | Startup readiness check only (not exposed to the model) |
| \`qloo_find_tags\` | Natural-language concept to Qloo tag URNs | Turning "translated fiction" or "cozy mystery" into tags |
| \`qloo_describe\` | Resolve one entity by name or id | Confirming what a patron-supplied title is |
| \`qloo_recommend\` | Entities related to a taste profile (signals + location + demographic + filters) | Books for fans of each show/artist/game, per place and audience |
| \`qloo_rank\` | Rank up to 10 supplied options for one profile | Ordering the buy/feature shortlist for the audience |
| \`qloo_where_popular\` | Geographic heat for one entity within an area | Local fit of a top title |
| \`qloo_trends\` | Time series for up to 5 entities over a date range | Rising vs fading |
| \`qloo_compare_audiences\` | Two groups of entity signals compared | Finding a title that bridges two shows or two patron groups |
| \`qloo_entity_tags\` | Tags that jointly characterise entities | Saying what a show and a book share |
| \`qloo_audience_demographics\` | Demographic distribution for an entity | Available to the agent; not part of the default workflow |

${tools.map(toolSection).join("\n")}
## Behaviour verified in the harness source (v${harnessVersion})

These facts come from reading \`@qloo/qloo-harness/dist\`; they are not in the tool descriptions.

- **No input validation at the MCP layer.** Invalid arguments surface only as \`MCP_ADAPTER_FAILURE\` (non-retryable) with no reason.
  Shelfwise therefore validates every call against the schemas above (plus the trend-date and demographic-needs-location rules) before calling.
- **Without a key:** \`tools/list\` and \`qloo_capabilities\` work (\`adapter.ready: false\`). Every workflow tool returns \`status: "error"\`, \`error.code: "QLOO_AUTH"\`, \`retryable: false\`.
- **Entity inputs are resolved by name** (Qloo search). Ambiguous or unknown names return \`status: "needs_input"\` with \`resolution.issues[]\`:
  \`{ input, kind: "ambiguous" | "not_found", input_kind: "entity" | "tag", field, candidates: [{ id, name, type, rank, score, popularity, parent_types, description, release_year }] }\`
  (up to 5 candidates). Passing a Qloo entity UUID instead of a name skips the search. A \`needs_input\` with an empty \`issues\` array is a plain "input incomplete" message.
- **\`demographic\`** is parsed by the harness into Qloo's \`signal.demographics.gender\` and \`signal.demographics.age\`. Age buckets are fixed:
  \`24_and_younger, 25_to_29, 30_to_34, 35_to_44, 45_to_54, 55_and_older\`. "teens", "teenagers" and "gen z" all map to \`24_and_younger\`; "young" to \`24_and_younger,25_to_29\`;
  "millennials" to \`30_to_34,35_to_44\`; explicit ranges ("25-34", "over 55") map to the overlapping buckets. A phrase it cannot map returns \`needs_input\`.
  **\`demographic\` requires \`signal_location\`** ("Demographic Qloo signals require signal_location so the audience geography is explicit").
- **Locations are free text** passed straight to Qloo (\`signal.location.query\`, \`filter.location.query\`). The harness does no place disambiguation.
- **\`recommend\`** sends \`filter.type\`, \`signal.interests.entities\`, \`signal.interests.tags\` (tag operator defaults to **intersection**), \`signal.location.query\`, demographics,
  \`filter.location.query\`, \`filter.tags\` / \`filter.exclude.tags\`, and \`feature.explainability\` (default on).
- **\`rank\`** sends \`filter.results.entities\` (the options) and \`take = number of options\`. The tool description warns scores from separate calls are not comparable.
- **\`where_popular\`** is a heatmap query (\`filter.type=urn:heatmap\`, the entity as \`signal.interests.entities\`, \`filter.location.query = within\`). Results are the raw heatmap points, sorted by \`query.affinity\`.
- **\`trends\`** calls \`/v2/trending\` once **per entity**. Output is under \`series[]\` (\`{ entity, points[] }\`), not \`results\`; \`points\` are passed through unnormalised, and the status is \`ok\` even when \`points\` is empty.
- **\`compare_audiences\`** returns the raw (size-bounded) \`/v2/analysis/compare\` \`results\`; its shape is not normalised by the harness.
- **Entity result shape** (recommend, rank, describe): \`{ entity_id, name, type, subtype, popularity, affinity, explainability?, properties? }\` where \`properties\` is limited to
  \`description, short_description, release_year, release_date, content_rating, duration, image, geocode, address, price_level, business_rating\`.
- **Transport:** MCP protocol \`2024-11-05\` over stdio, one JSON result per call (\`structuredContent\` and \`content[0].text\`), \`isError: true\` when \`status\` is \`error\`.
- **Quota:** one tool call can fan out into several upstream requests (a search per named input; one trending request per entity), so Qloo's quota is consumed faster than the call count suggests.

## Gap analysis: Shelfwise design vs. what the tool surface supports

Supported as designed: a \`book\` entity type (\`target_type\`, \`option_type\`, \`entity_type\`); cross-domain signals (TV, film, music, games, podcasts, books) in one recommend call;
place conditioning (\`signal_location\`); ambiguity handling (\`needs_input\` with candidates); audience ranking (\`qloo_rank\`); geographic heat (\`qloo_where_popular\`); time series (\`qloo_trends\`); two-group comparison (\`qloo_compare_audiences\`).

Gaps and limits (Shelfwise states these in the UI and README rather than papering over them):

1. **Age bands are coarse.** Qloo's youngest band is "24 and younger"; there is no separate teen, child or middle-grade audience. "Make it for teens" is therefore "24 and younger" in Qloo's terms, and children's collections cannot be targeted. Any age focus also requires a place.
2. **No book metadata beyond title and (sometimes) year.** The harness does not return author, ISBN, publisher, format, price, page count or availability. Shelf-talkers show title (and year when returned); staff must look titles up in their own catalogue or vendor. Budget arithmetic uses only an average price the user types in.
3. **"Local fit" is two different things.** \`signal_location\` re-weights a recommendation toward a place; \`qloo_where_popular\` returns geographic heat points for one entity. The point shape is not normalised by the harness, and whether Qloo has heatmap data for book entities is not documented there. **Unverified until a live key is available.**
4. **Trend and compare payload shapes are unverified.** Both are raw pass-throughs. Shelfwise reads them defensively (it needs dated points and a numeric metric to call a direction; otherwise it reports "unknown") and the sample-data shapes are best guesses.
5. **No per-item attribution in multi-signal calls** beyond the optional, unverified-shape \`explainability\`. Shelfwise makes one \`qloo_recommend\` call per signal so "Loved X? Try Y" is true by construction.
6. **No holdings or circulation data.** Qloo is taste data; Shelfwise cannot tell what a branch already owns.
7. **No place disambiguation** (free text), so an ambiguous place name is Qloo's to resolve.
8. **"Translated fiction" has no dedicated filter**; it relies on \`include_tags\` text resolution (\`qloo_find_tags\`). Verify live that a suitable tag exists.
`;
writeFileSync(path.join(root, "docs/qloo-tools.md"), md);
console.log(`wrote docs/qloo-tools.md and src/qloo/fixtures/tools.snapshot.ts (${tools.length} tools, harness ${harnessVersion})`);
